### ISSUE TITLE
route session sso  gives 404

### ISSUE THREAD

**Issue by muhzak** [spinen/laravel-discourse-sso#14] opened 2019-06-01 18:16 UTC
So I have it setup. I go to the discourse site, it redirects me to laravel site. I sign in -- it goes to discourse site and redirects back to mylaravelsite.com/session/sso_login?sso=**** 

This gives me a 404. 

Any routes I should be adding? I do have use laravel spark.

**Comment by jimmypuckett** [comment] 2019-06-01 18:28
@muhzak I am sorry that you are having that issue.  The routes get setup by the service provider...

https://github.com/spinen/laravel-discourse-sso/blob/145da7fdce0d56008b6b2c2ac73ed234eb103a32/src/SsoServiceProvider.php#L25

Did you add the `discourse` key to your `config/services.php` per the readme?

Can you post the output of your `route:list` as it relates to the discourse routes?

**Comment by muhzak** [comment] 2019-06-07 15:45
I have the discourse key in, the only route I have that starts with
discource is:

GET|HEAD  | discourse/sso | sso.login    |
Spinen\Discourse\Controllers\SsoController@login| web,auth     |

**Comment by jimmypuckett** [comment] 2019-06-08 15:58
That looks good.  Did you setup the SSO parameters in Discourse...

https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045

**Comment by jimmypuckett** [comment] 2019-06-25 23:59
@muhzak I am closing this due to inactivity.  If you find an issue, then please feel free to reopen.

**Comment by ahmedmaazin** [comment] 2020-06-06 03:46
Hi @jimmypuckett,

I'm having the same issue as above. Getting `404`. 

Below you can see the result of `route:list`

<img width="1461" alt="Screenshot 2020-06-06 at 11 42 07" src="https://user-images.githubusercontent.com/4073159/83935294-ed153f80-a7ea-11ea-928a-73f4ee5e003b.png">

The package shows up on `package:discover` as well. Re-installed multiple times as well. 

Laravel version 5.7 is what I'm on right now.

Thank you in advance.

**Comment by ahmedmaazin** [comment] 2020-06-06 03:55
After I posted the issue, I noticed the `action` was missing a `\` starting backward slash. 

`Spinen\Discourse\Controllers\SsoController@login` to `\Spinen\Discourse\Controllers\SsoController@login`

Adding that fixed the `404` issue. Please verify if this is the issue.

Thanks in advance.

**Comment by jimmypuckett** [comment] 2020-06-06 19:34
@ahmedmaazin Where is this missing that you made this change?

**Comment by ahmedmaazin** [comment] 2020-06-07 06:33
@jimmypuckett 

Here: https://github.com/spinen/laravel-discourse-sso/blob/develop/src/SsoServiceProvider.php#L28

**Comment by jimmypuckett** [comment] 2020-06-07 11:06
@ahmedmaazin We cannot recreate the issue.  I am trying to do any research on if putting the slash with have adverse effects on those that are not having this issue.

Can you tell me a little about your environment so can try to find a pattern?  What version of php, what OS, anything unique in your composer.json file, etc...

@muhzak If you are still following this thread, could you see if putting the `\` at the from of `Spinen\Discourse\Controllers\SsoController@login` in the `SsoServiceProvider` also solves the problem?

I am reopening this issue as we try to flush out the root cause.

Thanks.

**Comment by jimmypuckett** [comment] 2020-06-07 11:06
Tag @ssfinney

**Comment by ahmedmaazin** [comment] 2020-06-08 03:58
@jimmypuckett 

Local: 
PHP version: PHP 7.4.6
Laravel Framework 5.7.29

Server:
PHP version: PHP 7.3.1-1+ubuntu18.04.1+deb.sury.org+1
Laravel Framework 5.7.29

I don't have anything unique on my composer. However I realised I missed telling you that the issue happens only on my server (APP_ENV=prod). In my local env (APP_ENV=local) it works well without any change. 

Something is up with the package auto discovery. 

Let me know if this helps.

Thanks,

**Comment by ssfinney** [comment] 2020-06-08 14:17
Could also try this: 

Do the import of the SsoController at the top.
```php
use Spinen\Discourse\Controllers\SsoController;
```

Then on that line:
```php
'uses' => SsoController::class . '@login',
```

**Comment by ssfinney** [comment] 2020-07-27 13:34
@ahmedmaazin does the above solution work? It looks cleaner & safer to me than just putting the extra '\' at the front. If you could help us test that out, it would be greatly appreciated!

**Comment by ssfinney** [comment] 2020-08-04 18:53
Closing, will reopen if new comments come in

**Closed as completed by ssfinney** 2020-08-04 18:53 UTC
Labels: question
